# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  server:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.18]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
       
      - working-directory: ./myapp
        run: npm ci
      - working-directory: ./myapp
        run: npm run build --if-present
      - working-directory: ./myapp
        run: npm test
  build:
    name: Swift ${{ matrix.swift }} on ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        swift: ["5.7"]
    runs-on: ${{ matrix.os }}
    

    steps:
    - uses: actions/checkout@v3
    - name: get dirction
      run: pwd
   
   
    - name: Build
      working-directory: ./MyLibrary
      run: swift build -v
    - name: Run tests
      working-directory: ./MyLibrary
      run: swift test -v
    - name: get dirction
      run: pwd
